name = "crossbar"
version = "1.4.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.

description = "Cross-platform data validation library for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "aosasona", repo = "crossbar" }

internal_modules = ["crossbar/internal/*"]

[dependencies]
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_stdlib = ">= 0.65.0 and < 1.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.8.0 and < 2.0.0"
